name: my Github Actions Workflow
on: [push]
jobs:
  testing_github: 
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello,Running Github Actions"     # Add your test commands here 
      - name: Display repo name
        run:  echo "this workflow is running in ${{ github.repository}}"  # Add your test commands here 
